config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    get :profile, on: :collection

    member do
      patch :block
      patch :unblock
    end
  end

  root "home#index"

  resources :manager_emails, only: %i(create destroy)

  resources :companies, only: %i( new create show edit update index) do
    resources :multiple_recharges, only: %i(index new create)
    resources :recharge_histories, only: %i(index new create)
    resources :departments, only: %i(index new create show update edit) do
      resources :employee_profiles, only: %i(new create show edit update) do
        collection do
          post :create_card
          get :new_manager
          post :create_manager
          get :new_fired
          post :fired
        end
        member do
          patch :deactivate_card
          patch :activate_card
        end
      end
      resources :positions, only: %i(index new create show edit update)
    end
    collection do
      get :inactives
      get :search
    end

    member do
      put :activate
      put :deactivate
      get :manager
    end
  end

  namespace :api do
    namespace :v1 do
      resources :companies, only: %i[show index]
      resources :employee_profiles, only: %i(index)
    end
  end
end

app/models/employee_profile.rb
class EmployeeProfile < ApplicationRecord
  belongs_to :department
  belongs_to :user, optional: true
  belongs_to :position

  has_many :recharge_histories, dependent: :nullify, inverse_of: :employee_profile
  has_one :company, through: :department

  before_validation :format_phone_number
  before_validation :clean_cpf

  validates :name, :cpf, :rg, :address, :email, :phone_number, :status, :birth_date, :admission_date,
            :marital_status, presence: true
  validates :cpf, uniqueness: true
  validates :rg, uniqueness: true
  validates :email, uniqueness: true
  validates :dismissal_date, comparison: { greater_than: Time.zone.today }, if: :dismissal_is_present?
  validates :phone_number, length: { is: 11 }

  validate :check_if_full_name
  validate :check_company_domain
  validate :check_birth_date
  validate :check_admission_date

  enum status: { unblocked: 0, blocked: 5, fired: 10 }, _default: :unblocked
  enum marital_status: { single: 1, married: 4, widower: 8, divorced: 10 }

  private

  def dismissal_is_present?
    dismissal_date.present?
  end

  def format_phone_number
    phone_number&.gsub!(/\D/, '')
  end

  def clean_cpf
    cpf&.gsub!(/\D/, '')
  end

  def check_if_full_name
    return false if name&.match?(/\A[\p{L}]+(\s[\p{L}]+)+\z/)

    errors.add(:name, 'deve conter apenas letras e ter no mínimo duas palavras')
  end

  def check_company_domain
    company_domain = department&.company&.domain

    return false if email.blank? || email.ends_with?(company_domain)

    errors.add(:email, 'deve ser do mesmo domínio da empresa')
  end

  def check_birth_date
    errors.add(:birth_date, 'deve ser no mínimo 18 anos atrás') if birth_date.present? && birth_date > 18.years.ago
  end

  def check_admission_date
    if admission_date.present? && admission_date < birth_date + 18.years
      errors.add(:admission_date, 'deve ser no mínimo 18 anos depois da data de nascimento')
    elsif admission_date.present? && admission_date > Time.zone.today
      errors.add(:admission_date, 'deve ser anterior ou igual à data atual')
    end
  end
end

app/controllers/api/v1/employee_profiles_controller.rb
class Api::V1::EmployeeProfilesController < Api::V1::ApiController
  def index
    employee_profiles = if params[:cpf]
                          EmployeeProfile.where(cpf: params[:cpf])
                        elsif params[:status]
                          EmployeeProfile.where(status: params[:status])
                        else
                          EmployeeProfile.all
                        end

    render status: :ok, json: format_employee_profile(employee_profiles) unless employee_profiles.empty?
  end

  private

  def format_employee_profile(employee_profiles)
    employee_profiles.map do |profile|
      {
        id: profile.id,
        name: profile.name,
        cpf: profile.cpf,
        status: profile.status,
        company_cnpj: profile.department.company.registration_number
      }
    end
  end
end

app/controllers/employee_profiles_controller.rb
class EmployeeProfilesController < EmployeeCardApiController
  before_action :company_is_active?, only: %i[new create]
  before_action :set_employee_profile_data, only: %i[create_manager]
  before_action :set_position_and_department_for_employee, only: %i[create_manager]
  skip_before_action :profile_check

  def new_manager
    @employee_profile = EmployeeProfile.new
    @manager = ManagerEmails.find_by(email: current_user.email)
  end

  def create_manager
    return redirect_to root_path, notice: t('.success') if @employee_profile.save

    flash.now[:alert] = t('.failure')

    @manager = ManagerEmails.find_by(email: current_user.email)
    render :new_manager
  end

  def new
    @employee_profile = EmployeeProfile.new
  end

  def create
    @employee_profile = EmployeeProfile.new(employee_profile_params)
    @employee_profile.department_id = @department.id

    return redirect_to [@company, @department, @employee_profile], notice: t('.success') if @employee_profile.save

    flash.now[:alert] = t('.failure')
    render :new
  end

  private

  def company_is_active?
    return false if @company.active

    redirect_to root_path, alert: t('inactive_company')
  end

  def set_employee_profile_data
    @employee_profile = EmployeeProfile.new(manager_profile_params)
    @employee_profile.user_id = current_user.id
    @employee_profile.email = current_user.email
    @employee_profile.cpf = current_user.cpf
  end

  def set_position_and_department_for_employee
    @employee_profile.department_id = @department.id
    @employee_profile.position = Position.where(name: 'Gerente').where(department_id: @department.id).first
  end

  def employee_profile_params
    params.require(:employee_profile).permit(:name, :social_name, :rg, :cpf, :email,
                                             :address, :birth_date, :phone_number,
                                             :admission_date, :dismissal_date, :marital_status,
                                             :status, :position_id, :user_id)
  end

  def manager_profile_params
    params.require(:employee_profile).permit(:name, :social_name, :rg, :cpf, :email,
                                             :address, :birth_date, :phone_number,
                                             :admission_date, :dismissal_date, :marital_status,
                                             :status, :user_id)
  end
end

app/views/employee_profiles/_form.html.erb
<div class="card shadow-sm p-3 mb-5 bg-body rounded m-3">
  <div class="card-body">
    <% if @employee_profile.errors.present? %>
      <%= render "shared/errors", errors: @employee_profile.errors %>
    <% end %>
    <h4 class="card-title"><%= title %> - <%= @department.name %></h4>
    <%= form_with model: [@company, @department, @employee_profile], data: { turbo: false }  do |f| %>

      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="mb-3">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="mb-3">
            <%= f.label :social_name, class: 'form-label' %>
            <%= f.text_field :social_name, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="mb-3 col-lg-4 col-md-12">
          <%= f.label :email, class: 'form-label' %>
          <%= f.text_field :email, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-2 col-md-12">
            <%= f.label :birth_date, class: 'form-label' %>
            <%= f.date_field :birth_date, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-3 col-md-12">
          <%= f.label :cpf, class: 'form-label' %>
          <%= f.text_field :cpf, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-3 col-md-12">
          <%= f.label :rg, class: 'form-label' %>
          <%= f.text_field :rg, class: 'form-control'%>
        </div>
      </div>
      
      <div class="mb-3">
        <%= f.label :address, class: 'form-label' %>
        <%= f.text_field :address, class: 'form-control'%>
      </div>

      <div class="row">
        <div class="mb-3 col-lg-6 col-md-12">
            <%= f.label :marital_status, class: 'form-label' %>:
            <%= f.select :marital_status, EmployeeProfile.marital_statuses.keys.map { |s| [I18n.t("activerecord.enum.employee_profile.marital_status.#{s}"), s] }, {}, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-6 col-md-12">
            <%= f.label :phone_number, class: 'form-label' %>
            <%= f.text_field :phone_number, class: 'form-control', placeholder: '(00) 00000-0000' %>

        </div>
      </div>
      
      <div class="row">
        <div class="col-lg-4 col-md-12">
          <div class="mb">
            <%= f.label :admission_date, class: 'form-label' %>
            <%= f.date_field :admission_date, class: 'form-control'%>
          </div>
        </div>
        <div class="col-lg-4 col-md-12">
          <%= f.label :department_id, class: 'form-label' %>:
          <select class="form-select" disabled>
            <option selected><%= @department.name %></option>
          </select>
        </div>
        <div class="col-lg-4 col-md-12">
          <%= f.label :position_id, class: 'form-label' %>:
          <%= f.select :position_id, @department.positions.where.not(name: 'Gerente').collect { |p| [p.name, p.id] }, { prompt: 'Não selecionado' }, class: 'form-select' %>
        </div>
      </div>
      <div class="d-flex w-100">
        <%= f.submit t('.save'), class: 'mt-3 btn btn-success ms-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/employee_profiles/edit.html.erb
<%= render 'form', title: 'Edição de Perfil' %>

app/views/employee_profiles/new.html.erb
<%= render 'form', title: 'Cadastro de Funcionário' %>

app/views/employee_profiles/new_fired.html.erb
<div class="card shadow-sm p-3 mb-5 bg-body rounded m-3 ">
  <div class="card-body">
    <% if @employee_profile.errors.present? %>
      <%= render "shared/errors", errors: @employee_profile.errors %>
    <% end %>
    <h4 class="card-title">Desligamento do Funcionário</h4>
    <p>Nome: <%= @employee_profile.name %></p>
    <p>Email: <%= @employee_profile.email %></p>
    <p>CPF: <%= @employee_profile.cpf %></p>
    <hr>
    <%= form_with url: fired_company_department_employee_profiles_path(@company, @department, id: @employee_profile), data: { turbo: false }  do |f| %>
      <div class="mb-3 col-lg-3 col-md-4 col-12">
        <label for="fired_date"><%= t('.dismissal_date') %></label>

        <input type="date" id="fired_date" name="fired[date]" class="form-control mt-2">
      </div>
      <%= f.submit t('.fired'), class: 'mt-3 btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/employee_profiles/new_manager.html.erb
<div class="card shadow-sm p-3 mb-5 bg-body rounded m-3">
  <div class="card-body">
    <% if @employee_profile.errors.present? %>
      <%= render "shared/errors", errors: @employee_profile.errors %>
    <% end %>
    <h4 class="card-title">Atualização de cadastro</h4>
    <%= form_with model: [@company, @department, @employee_profile], data: { turbo: false }, url: create_manager_company_department_employee_profiles_path do |f| %>

      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="mb-3">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="mb-3">
            <%= f.label :social_name, class: 'form-label' %>
            <%= f.text_field :social_name, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="mb-3 col-lg-4 col-md-12">
          <%= f.label :email, class: 'form-label' %>
          <%= f.text_field :email, class: 'form-control', value: current_user.email, readonly: true %>
        </div>
        <div class="mb-3 col-lg-2 col-md-12">
            <%= f.label :birth_date, class: 'form-label' %>
            <%= f.date_field :birth_date, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-3 col-md-12">
          <%= f.label :cpf, class: 'form-label' %>
           <%= f.text_field :cpf, class: 'form-control', value: current_user.cpf, readonly: true %>
        </div>
        <div class="mb-3 col-lg-3 col-md-12">
          <%= f.label :rg, class: 'form-label' %>
          <%= f.text_field :rg, class: 'form-control'%>
        </div>
      </div>
      
      <div class="mb-3">
        <%= f.label :address, class: 'form-label' %>
        <%= f.text_field :address, class: 'form-control'%>
      </div>

      <div class="row">
        <div class="mb-3 col-lg-6 col-md-12">
            <%= f.label :marital_status, class: 'form-label' %>:
            <%= f.select :marital_status, EmployeeProfile.marital_statuses.keys.map { |s| [I18n.t("activerecord.enum.employee_profile.marital_status.#{s}"), s] }, {}, class: 'form-control'%>
        </div>
        <div class="mb-3 col-lg-6 col-md-12">
            <%= f.label :phone_number, class: 'form-label' %>
            <%= f.text_field :phone_number, class: 'form-control'%>
        </div>
      </div>
      
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="mb">
            <%= f.label :admission_date, class: 'form-label' %>
            <%= f.date_field :admission_date, class: 'form-control'%>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <%= f.label :department_id, class: 'form-label' %>:
          <select class="form-select" disabled>
            <option selected><%= @department.name %></option>
          </select>
        </div>
        
      </div>
      <div class="d-flex w-100">
        <%= f.submit t('.save'), class: 'mt-3 btn btn-success ms-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/employee_profiles/show.html.erb
<h3 class="mt-3">Visualizando perfil de funcionário</h3>
<%= render('shared/profile/info')%>
<%= render('shared/profile/company')%>
<%= render('shared/profile/card')%>