config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    get :profile, on: :collection

    member do
      patch :block
      patch :unblock
    end
  end

  root "home#index"

  resources :manager_emails, only: %i(create destroy)

  resources :companies, only: %i( new create show edit update index) do
    resources :multiple_recharges, only: %i(index new create)
    resources :recharge_histories, only: %i(index new create)
    resources :departments, only: %i(index new create show update edit) do
      resources :employee_profiles, only: %i(new create show edit update) do
        collection do
          post :create_card
          get :new_manager
          post :create_manager
          get :new_fired
          post :fired
        end
        member do
          patch :deactivate_card
          patch :activate_card
        end
      end
      resources :positions, only: %i(index new create show edit update)
    end
    collection do
      get :inactives
      get :search
    end

    member do
      put :activate
      put :deactivate
      get :manager
    end
  end

  namespace :api do
    namespace :v1 do
      resources :companies, only: %i[show index]
      resources :employee_profiles, only: %i(index)
    end
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employee_profiles, dependent: :nullify
  belongs_to :department
  before_validation :set_code, on: :create
  has_one :company, through: :department
  validates :name, :description, :code, presence: true
  validates :code, uniqueness: true, format: { with: /\A[A-Z]{3}\d{3}\z/, message: :invalid_format }
  validates :standard_recharge, numericality: { greater_than_or_equal_to: 0 }

  private

  def set_code
    letters = ('A'..'Z').to_a.sample(3).join
    numbers = format('%03d', rand(1000))
    self.code = letters + numbers
  end
end

app/controllers/positions_controller.rb
require 'get_card_type'

class PositionsController < ApplicationController
  before_action :require_manager
  before_action :status_api
  before_action :set_company_and_department, only: %i[index show new edit create update]
  before_action :set_position, only: %i[show edit update]
  before_action :set_card_types, only: %i[show new edit create update]

  def index
    @positions = Position.where(department_id: params[:department_id])
  end

  def show; end

  def new
    @position = Position.new
  end

  def edit; end

  def create
    @position = Position.new(position_params.merge(department: @department))

    return redirect_to [@company, @department, @position], notice: t('.success') if @position.save

    flash.now[:alert] = t('.failure')
    render :new
  end

  def update
    return redirect_to [@company, @department, @position], notice: t('.success') if @position.update(position_params)

    flash.now[:alert] = t('.failure')
    render :edit
  end

  private

  def set_position
    @position = Position.find(params[:id])
    @card_type = GetCardType.find(@position.card_type_id, @company.registration_number)

    can_access_position
  end

  def set_company_and_department
    @company = Company.find(params[:company_id])
    @department = @company.departments.find(params[:department_id])
  end

  def set_card_types
    @card_types = GetCardType.all(@company.registration_number)
  end

  def position_params
    params.require(:position).permit(:name, :description, :card_type_id, :standard_recharge)
  end

  def can_access_position
    return if current_user.employee_profile.company.id == @position.company.id

    flash[:alert] = t('forbidden')
    redirect_to root_path
  end
end

app/views/positions/_form.html.erb
<div class="card mt-2 shadow-sm p-3 mb-5 bg-body rounded">
  <div class="card-body">
    <% if @position.errors.present? %>
      <%= render "shared/errors", errors: @position.errors %>
    <% end %>
    <h4 class="card-title">Novo Cargo</h4>
    <%= form_with(model: [@company, @department, @position], data: { turbo: false }) do |f| %>
        <div class="mb-3">
          <%= f.label :name, class: 'form-label' %>
          <%= f.text_field :name, class: 'form-control', disabled: (@position.name == 'Gerente') %>
        </div>
      <div class="mb-3">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_field :description, class: 'form-control'%>
      </div>
      <div class="mb-3">
        <%= f.label :standard_recharge, class: 'form-label' %> (R$)
        <%= f.number_field :standard_recharge, class: 'form-control'%>
      </div>
      <div class="mb-3">
        <%= f.label :card_type_id, class: 'form-label' %>
        <div class="col-lg-4 col-md-12">
          <%= f.select :card_type_id, @card_types.collect { |p| [p.name, p.id] }, { prompt: 'Não selecionado' }, { class: 'form-select', disabled: @position.employee_profiles.where(card_status: true).any? } %>
        </div>
      </div>
      <%= f.submit t('.save'), class:'btn btn-success'%>
    <% end %>
  </div>
</div>

app/views/positions/edit.html.erb
<%= render 'form' %>

app/views/positions/index.html.erb
<div class="text-center w-100 mt-2">
  <p class="fs-1"><%= @department.name %> </p>
  <div class="d-flex align-items-center mb-2 justify-content-center">
    <%= link_to company_department_path(company_id: @company.id, id: @department.id), class: "btn btn-primary btn-sm d-inline  py-0 px-2 me-3", style:'font-size:20px;' do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>
    <p class="fs-3 m-0 d-inline">Lista de cargos</p>
  </div>
</div>

<% if @positions.any? %>
  <div class="d-flex flex-wrap justify-content-center" >
    <% @positions.each do |position| %>
      <div class="card m-3 w-20" style="width: 18rem;" id="position<%=position.id%>">
        <div class="card-body">
          <h5 class="card-title"><%= position.name %></h5>
          <p class="card-text m-1"><%= position.description %></p>
          <p class="card-text m-1">Funcionários no cargo: <%= position.employee_profiles.count %> </p>
        </div>
        <div class="card-footer">
          <a href="<%= company_department_position_path(company_id: @company.id, department_id: @department.id, id: position.id) %>" class="btn w-100 btn-primary mt-2">
              <i class="bi bi-eye"></i>
              Ver cargo
          </a>
        </div>
      </div>
    <% end %>
  </div> 
<% else %>
  <div class="mt-5">
    <h3>Nenhum cargo neste departamento.</h3>
  </div>
<% end %>

app/views/positions/new.html.erb
<%= render 'form' %>

app/views/positions/show.html.erb
<div class="card mt-2 shadow-sm bg-body rounded">
  <div class="card-body">
    <h2 class="card-title"><%= Position.human_attribute_name('name') %>: <%=  @position.name %></h2>
    <p class="card-text"><%= Position.human_attribute_name('description') %>: <%= @position.description %></p>
    <p class="card-text"> <%= Position.human_attribute_name('code') %>: <%= @position.code %></p>
    <p class="card-text"><%= Position.human_attribute_name('standard_recharge') %>: 
    <%= number_to_currency(@position.standard_recharge) %></p>
    <% card_name = @card_type.nil? ? 'Cartão Inválido' : @card_type.name %>
    <p class="card-text"><%= Position.human_attribute_name('card_type_id')%>: <%= card_name %></p>
    <p class="card-text"><%= Position.human_attribute_name('department') %>: <%= @position.department.name %></p>
    <p class="card-text"><%= Position.human_attribute_name('company') %>: <%= @position.department.company.brand_name %></p>
    

    <%= link_to t('.edit'), edit_company_department_position_path(@department.company_id, @department.id), id: 'btn_edit', class: 'btn btn-warning text-white bold' if @department.present? do%>
    <% end %>
    <%= link_to t('.new_employee'), new_company_department_employee_profile_path(company_id: @department.company_id, department_id: @department.id), id: 'btn_edit', class:'btn btn-primary'%>
    <%= link_to t('.list_positions'), company_department_positions_path(company_id: @department.company_id), id: 'btn_edit', class:'btn btn-primary'%>
    <%= link_to t('.see_department'), company_department_path(company_id: @department.company_id, id: @department.id), id: 'btn_edit', class:'btn btn-primary'%>
  </div>
</div>

<% if @position.employee_profiles.any? %>
  <h3 class="mt-3">Funcionários neste cargo:</h3>
  <table class="table table-striped table-bordered rounded mt-2">
    <thead class="text-center">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Email</th>
        <th scope="col">Cargo</th>
        <th scope="col">Status</th>
        <th scope="col">Ações</th>
      </tr>
    <thead>
    <tbody id="employees">
      <% @position.employee_profiles.each do |employee| %>
        <tr id="employee[<%= employee.id%>]">
          <td class="align-baseline"><%= employee.name %></td>
          <td class="align-baseline"><%= format_cpf(employee.cpf) %></td>
          <td class="align-baseline"><%= employee.email %></td>
          <td class="align-baseline"><%= employee.position.name %></td>
          <td class="align-baseline text-center ">
            <div class="alert p-1 m-0 <%= employee.unblocked? ? 'alert-success' : 'alert-danger' %>">
              <%= t(employee.status) %>
            </div>
          </td>
          <td class="d-flex justify-content-around">
            <%= button_to create_card_company_department_employee_profiles_path(
                  company_id: @department.company_id, department_id: @department.id, card: { cpf: employee.cpf, company_card_type_id: employee.position.card_type_id }),
                            method: :post, id: "post#{employee.id}", class: (employee.card_status? || @card_type.nil? ? 'btn btn-primary disabled' : 'btn btn-primary'),
                            disabled: employee.card_status ? true : false do %>
              Solicitar Cartão
            <% end %>


            <%= link_to company_department_employee_profile_path(
              company_id: @department.company.id,
              department_id: @department.id,
              id: employee.id
            ),
            class: 'btn btn-primary d-inline', method: :get do %>
              Detalhes
              <i class="bi bi-eye"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="mt-3">Não há funcionários nesta posição até o momento.</h3>
<% end %>