config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    get :profile, on: :collection

    member do
      patch :block
      patch :unblock
    end
  end

  root "home#index"

  resources :manager_emails, only: %i(create destroy)

  resources :companies, only: %i( new create show edit update index) do
    resources :multiple_recharges, only: %i(index new create)
    resources :recharge_histories, only: %i(index new create)
    resources :departments, only: %i(index new create show update edit) do
      resources :employee_profiles, only: %i(new create show edit update) do
        collection do
          post :create_card
          get :new_manager
          post :create_manager
          get :new_fired
          post :fired
        end
        member do
          patch :deactivate_card
          patch :activate_card
        end
      end
      resources :positions, only: %i(index new create show edit update)
    end
    collection do
      get :inactives
      get :search
    end

    member do
      put :activate
      put :deactivate
      get :manager
    end
  end

  namespace :api do
    namespace :v1 do
      resources :companies, only: %i[show index]
      resources :employee_profiles, only: %i(index)
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :logo
  has_many :departments, dependent: :destroy
  has_many :positions, through: :departments
  has_many :managers, dependent: :destroy
  validates :registration_number, uniqueness: true
  validates :brand_name, :corporate_name, :registration_number,
            :address, :phone_number, :email, :domain, :logo, presence: true
  before_validation :clean_registration_number

  def block_employee
    departments.each do |d|
      d.employee_profiles.each do |e|
        e.update(status: 'blocked')
        GetCardApi.deactivate(GetCardApi.show(e.cpf).id) if e.card_status
      end
    end
  end

  def active_employee
    departments.each do |d|
      d.employee_profiles.each do |e|
        e.update(status: 'unblocked')
        GetCardApi.activate(GetCardApi.show(e.cpf).id) if e.card_status
      end
    end
  end

  private

  def clean_registration_number
    registration_number&.gsub!(/\D/, '')
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::ApiController
  def index
    companies = if params[:cnpj]
                  Company.where(registration_number: params[:cnpj])
                elsif params[:active]
                  Company.where(active: params[:active])
                else
                  Company.all
                end

    return if companies.empty?

    render status: :ok, json: companies.as_json(only: %i[id registration_number brand_name corporate_name active])
  end

  def show
    company = Company.find(params[:id])
    render status: :ok, json: company.as_json(only: %i[id registration_number brand_name corporate_name active])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_admin, except: %i[show search]
  before_action :set_company, only: %i[show edit update activate deactivate manager]
  before_action :require_manager, only: %i[search]

  def index; end

  def show; end

  def manager
    @users = User.manager.joins(employee_profile: { department: :company }).where(companies: { id: @company.id })
    @manager = ManagerEmails.new
    used_emails = User.manager.all.pluck('email')
    @emails = ManagerEmails.active.where(company: @company).where.not(email: used_emails)
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    @company = Company.new company_params

    if @company.save
      department = @company.departments.create!(name: 'Departamento de RH', description: 'Recursos Humanos')
      department.positions.create!(name: 'Gerente', description: 'Gerente Geral', card_type_id: 1)

      return redirect_to @company, notice: t('.success')
    end

    flash.now[:alert] = t('.failure')
    render :new
  end

  def inactives
    @inactive_companies = Company.where(active: false)
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: t('.success')
    else
      flash.now[:notice] = t('.failure')
      render :edit
    end
  end

  def activate
    @company.active_employee if @company.update(active: true)
    redirect_to company_path(@company)
  end

  def deactivate
    @company.block_employee if @company.update(active: false)

    redirect_to company_path(@company)
  end

  def search
    company_id = current_user.department.company.id
    search_term = "%#{params[:search]}%"

    @employee_profiles = EmployeeProfile.joins(:department)
                                        .where(departments: { company_id: })
                                        .where('cpf LIKE :search OR employee_profiles.name LIKE
                                        :search OR employee_profiles.social_name LIKE :search', search: search_term)
  end

  private

  def set_company
    @company = Company.find(params[:id])

    return if current_user.admin?
    return if current_user.employee_profile.company.id == @company.id

    flash[:alert] = t('forbidden')
    redirect_to root_path
  end

  def company_params
    params.require(:company).permit(:brand_name, :corporate_name,
                                    :registration_number, :address,
                                    :phone_number, :email, :domain, :logo)
  end
end

app/views/companies/_edit_company_buttons.html.erb
<div class="card-footer d-flex justify-content-between  align-items-center">
  <%= link_to edit_company_path(@company), class: 'btn btn-warning text-white' do %>
    <i class="bi bi-pencil-square d-inline"></i> Editar
  <% end %>

  <%= link_to manager_company_path(@company), class: 'btn btn-primary text-white' do %>
    <i class="bi bi-person-badge d-inline"></i> Gerentes
  <% end %>

  <% if @company.active %>
    <%= button_to deactivate_company_path(@company), method: :put, form: { class: 'd-inline' }, class: 'btn btn-danger' do %>
      <i class="ms-auto bi bi-x-circle"></i> Desativar
    <% end %>
  <% end %>
  

  <% if !@company.active %>
    <%= button_to activate_company_path(@company), method: :put, form: { class: 'd-inline m-1' }, class: 'btn btn-success' do %>
      <i class="ms-auto bi bi-check-lg"></i> Ativar
    <% end %>
  <% end %>

</div>

app/views/companies/edit.html.erb
<%if @company.errors.any?%>
  <ul>
    <% @company.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <%end%>
  </ul>
<%end%>

<div class="card my-4">
    <div class="card-body">
      <h4 class="card-title">Editar Empresa</h4>
      <%= form_with model: @company do |f| %>
        <div class="mb-3">
          <%= f.label :brand_name, class: 'form-label' %>
          <%= f.text_field :brand_name, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :corporate_name, class: 'form-label' %>
          <%= f.text_field :corporate_name, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :registration_number, class: 'form-label' %>
          <%= f.text_field :registration_number, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :address, class: 'form-label' %>
          <%= f.text_field :address, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :phone_number, class: 'form-label' %>
          <%= f.text_field :phone_number, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: 'form-label' %>
          <%= f.text_field :email, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :domain, class: 'form-label' %>
          <%= f.text_field :domain, class: 'form-control'%>
        </div>
        <div class="mb-3">
          <%= f.label :logo, class: 'form-label' %>
          <%= f.file_field :logo, class: 'form-control'%>
        </div>
        <%= f.submit t('.save'), class: 'btn btn-success' %>
      <% end %>
    </div>
</div>

app/views/companies/inactives.html.erb
<% if @inactive_companies.any? %>
  <div class="d-flex flex-wrap justify-content-center">
    <% @inactive_companies.each do |company| %>
      <div class="card m-3 w-20" style="width: 18rem;">
        <img src="<%= url_for(company.logo) %>"class="card-img-top fixed-height" alt= <%= company.brand_name %> >
        <div class="card-body">
          <h5 class="card-title"><%= company.brand_name %></h5>
          <p class="card-text"><%= company.domain %></p>
          <a href="<%= company_path(company) %>" class="btn btn-primary">Ver Detalhes</a>
        </div>
      </div>
    <% end %>
  </div>
<% else  %>
  <div class="alert alert-warning mt-4">
    <p> Nenhuma empresa inativa </p>
  </div>
<% end %>

app/views/companies/manager.html.erb
<div class="row mt-3">
  <div class="col-12 text-center">
    <h2><%= @company.brand_name %></h2>
  </div>
  <div class="col-sm-6 mt-2">
    <div id="cadEmail" class="border border-1 p-3 rounded-top">
    <h4>Cadastro prévio de e-mails:</h4>
    <% if @manager.errors.any? %>
      <h2>Verifique os erros abaixo:</h2>
      <ul>
        <% @manager.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model:@manager, url:manager_emails_path do |f| %>
      <%= f.hidden_field :company_id, :value => @company.id%>
      <div class="input-group mb-3">
        <%= f.text_field :email, placeholder: 'Cadastrar email', class:'form-control' %>
        <%= f.submit 'Cadastrar', class:'btn btn-success' %>
      </div>
    <% end %>
    </div>

    <% if  @emails.present? %>
      <table class="table table-striped table-bordered", id = 'tabela'>
        <thead class="text-center">
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>

          <% @emails.each do |email| %>
            <tr>
              <td class="align-baseline"><%= email.email %></td>
              <td class="d-flex justify-content-around">

              <%= button_to manager_email_path(email.id), {method: :delete, id:"delete#{email.id}", form: { class: 'd-inline m-0' }, class:'btn btn-danger d-inline'} do %>
                <i class="bi bi-trash"></i>
              <% end %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    <% end %>
  </div>
  <div class="col-sm-6 mt-2">
    <div id="cadEmail" class="border border-1 p-3 rounded">
      <table>
        <thead>
          <h4> Gerentes Ativos: </h4>
          <tr>
            <th>E-mails:</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
                <td>
                  <div class ='action-buttons'>
                    <% unless user.blocked? %>
                      <%= button_to 'Bloquear Gerente', block_user_path(user), method: :patch, id: dom_id(user, 'block'), class: 'btn btn-success ms-3 mt-1' %>
                    <% else %>
                      <%= button_to 'Desbloquear Gerente', unblock_user_path(user), method: :patch, id: dom_id(user, 'unblock'), class: 'btn btn-danger ms-3 mt-1' %>
                    <% end %>
                  </div>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="col-3">
  <%= link_to 'Voltar', company_path(@company), class: 'btn btn-primary mt-3'%>
</div>

app/views/companies/new.html.erb
<div class="form-field mt-3">
  <div class="card shadow-sm p-3 mb-5 bg-body rounded m-3 ">
    <div class="card-body">
      <% if @company.errors.present? %>
        <%= render "shared/errors", errors: @company.errors %>
      <% end %>
      <%= form_with model: @company, data: { turbo: false }  do |f| %>
      <h4 class="card-title mb-5 ms-3">Nova Empresa</h4>
        <div class="card-inputs">
          <div class="col-5">
            <div class="mb-3">
              <%= f.label :brand_name, class: 'form-label' %>
              <%= f.text_field :brand_name, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :corporate_name, class: 'form-label' %>
              <%= f.text_field :corporate_name, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :registration_number, class: 'form-label' %>
              <%= f.text_field :registration_number, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :address, class: 'form-label' %>
              <%= f.text_field :address, class: 'form-control'%>
            </div>
          </div>
          <div class="col-5">
            <div class="mb-3">
              <%= f.label :phone_number, class: 'form-label' %>
              <%= f.text_field :phone_number, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :email, class: 'form-label' %>
              <%= f.text_field :email, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :domain, class: 'form-label' %>
              <%= f.text_field :domain, class: 'form-control'%>
            </div>
            <div class="mb-3">
              <%= f.label :logo, class: 'form-label' %>
              <%= f.file_field :logo, class: 'form-control'%>
            </div>
            <div class="w-100 d-flex">
              <%= f.submit t('.save'), class:'ms-auto btn btn-success' %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/companies/search.html.erb
<% if @employee_profiles.present? %>
  <h2 class="mt-2">Resultados da pesquisa:</h2>
  <table class="table table-striped table-bordered rounded mt-2">
    <thead class="text-center">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Cargo</th>
        <th scope="col">Departamento</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody class="text-center">
      <% @employee_profiles.each do |employee_profile| %>
        <tr>
          <td class="align-baseline text-start">
            <%= link_to format_name(employee_profile.name), company_department_employee_profile_path(employee_profile.department.company.id, employee_profile.department.id, employee_profile), class:'ms-2' %>
          </td>
          <td class="align-baseline"><%= format_cpf(employee_profile.cpf) %> </td>
          <td class="align-baseline"><%= employee_profile.position.name %></td>
          <td class="align-baseline"><%= employee_profile.department.name %></td>
          <td class="align-baseline text-center ">
            <div class="alert p-1 m-0 <%= employee_profile.unblocked? ? 'alert-success' : 'alert-danger' %>">
              <%= t(employee_profile.status) %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<div class="alert alert-warning mt-4">
  <p>Nenhum resultado encontrado</p>
</div>
<% end %>

app/views/companies/show.html.erb
<% if current_user.admin? || current_user.employee_profile.company == @company %>
  
  <div class="row">
    <div class="d-md-none d-lg-block col-lg-3">
    </div>
    
    <div class="col-md-12 col-lg-6">
      <div class="card my-4">
        <% if @company.logo.present? %>
          <%= image_tag @company.logo, class: 'card-img-top rounded rounded-bottom-0' %>
        <% end %>
        <div class="card-body p-0">
          <div class="card-header">
            <h3 class="card-title pt-2 ps-2"><%= @company.brand_name %></h2>
          </div>
          <h5 class="ms-1 mt-2 ps-3 mt-3">Dados cadastrais</h5>
          <div class="ms-1 ps-3">
            <p class="card-text mb-1 mt-2"><b><%= Company.human_attribute_name('corporate_name') %></b>: <%= @company.corporate_name %></p>
            <p class="card-text mb-1"> <b><%= Company.human_attribute_name('registration_number') %></b>: <%= format_cnpj(@company.registration_number) %></p>
            <p class="card-text mb-1"><b><%= Company.human_attribute_name('address') %></b>: <%= @company.address %></p>
            <p class="card-text mb-1"><b><%= Company.human_attribute_name('phone_number') %></b>: <%= @company.phone_number %></p>
            <p class="card-text mb-1"><b><%= Company.human_attribute_name('email') %></b>: <%= @company.email %></p>
            <p class="card-text mb-1"><b><%= Company.human_attribute_name('domain') %></b>: <%= @company.domain %></p>
            <p class="card-text mb-1"><b><%= Company.human_attribute_name('active') %></b>:
              <% if @company.active %>
                Ativo
              <% else %>
                Inativo
              <% end %>
            </p>
          </div>
        </div>
        <% if current_user.admin? %>
          <%= render 'edit_company_buttons'%>
        <% elsif current_user.manager? %>
          <div class="card-footer d-flex justify-content-between align-items-center">

            <%= link_to 'Recarregar Cartões', new_company_recharge_history_path(company_id: @company.id),
                        id: 'btn_new_recharge', class:'btn btn-primary text-white mx-auto'%>
            

            <%= link_to company_departments_path(@company), class: 'btn btn-primary text-white mx-auto' do %>
              <i class="bi bi-buildings d-inline"></i> Departamentos
            <% end %>

            <%= link_to new_company_department_path(current_user.employee_profile.company), class: 'btn btn-primary text-white mx-auto' do %>
              <i class="bi bi-plus-circle"></i> Cadastrar departamento
            <% end %>

          </div>
        <% end %>
      </div>
    </div>

    <div class="d-md-none d-lg-block col-lg-3">
    </div>
  </div>
  
<% end %>