config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    get :profile, on: :collection

    member do
      patch :block
      patch :unblock
    end
  end

  root "home#index"

  resources :manager_emails, only: %i(create destroy)

  resources :companies, only: %i( new create show edit update index) do
    resources :multiple_recharges, only: %i(index new create)
    resources :recharge_histories, only: %i(index new create)
    resources :departments, only: %i(index new create show update edit) do
      resources :employee_profiles, only: %i(new create show edit update) do
        collection do
          post :create_card
          get :new_manager
          post :create_manager
          get :new_fired
          post :fired
        end
        member do
          patch :deactivate_card
          patch :activate_card
        end
      end
      resources :positions, only: %i(index new create show edit update)
    end
    collection do
      get :inactives
      get :search
    end

    member do
      put :activate
      put :deactivate
      get :manager
    end
  end

  namespace :api do
    namespace :v1 do
      resources :companies, only: %i[show index]
      resources :employee_profiles, only: %i(index)
    end
  end
end

app/views/shared/profile/_card.html.erb
<div class="card my-3">
 <div class="card-header">
    <%= t('.title') %>
  </div>
  <div class="row g-0">
      <% unless @card_icon.nil?%>
        <div class="col-md-4">
          <h4 class="ms-3 mt-1">Cartão do cargo:</h4>
          <img src="<%= @card_icon %>" class="img-fluid rounded-start p-2">
        </div>
      <% end %>
    <div class="col-md-8">
      <h4 class="ms-3 mt-1">Seu cartão:</h4>
      <div class="card-body" id="user_card">
        <%if @employee_profile.card_status%>
          <%if @card.present?%>
            <h3><%= t('.card')%> <%=@card.name%></h3>
            <p class="m-1"><%= t('get_card_api.attributes.number')%>: <%=@card.number%></p>
            <p class="m-1"><%= t('get_card_api.attributes.points')%>: <%=@card.points%></p>
            <p class="m-1"><%= t('.status')%>: <%=t("get_card_api.attributes.status.#{@card.status}")%></p>

            <%= link_to company_recharge_histories_path(@employee_profile.department.company,
                                                        params: { employee: @employee_profile }),
                                                        class:'btn btn-primary' do%>
                <i class="bi bi-receipt"></i>
                <%= RechargeHistory.model_name.human %>
            <% end %>

            <% if current_user.manager? %>
              <div id="recharge_card" style="margin: 10px 0;">
                <%if @employee_profile.card_status & @card.present? & @employee_profile.unblocked? %>
                  <%= link_to t('.new_recharge'),
                              new_company_recharge_history_path(
                                company_id: @employee_profile.department.company_id,
                                cpf: @employee_profile.cpf),
                              id: 'btn_new_recharge', class:'btn btn-primary'%>
                <% end %>
              </div>
            <% end %>

            <div style="margin: 10px 0;">
              <% if current_user.manager? && @employee_profile.user != current_user %>
                <%if @card&.status == 'active'%>
                  <%= button_to deactivate_card_company_department_employee_profile_path(company_id: @company.id,
                                                                            department_id: @department.id,
                                                                            id: @employee_profile.id),
                                                                            form: {class:'d-inline'},
                                                                            method: :patch,
                                                                            class:'btn btn-danger' do %>
                    <i class="bi bi-x-lg"></i>
                    <%= t('.block_card')%>
                  <% end %>
                <%else%>
                  <%= button_to t('.unblock_card'),
                    activate_card_company_department_employee_profile_path(company_id: @company.id,
                                                                          department_id: @department.id,
                                                                          id: @employee_profile.id),
                                                                          form: {class:'d-inline'},
                                                                          method: :patch,
                                                                          class:'btn btn-danger text-white'%>
                <%end%>
              <% end %>
            </div>
          <%else%>
            <%= t('.unavailable')%>
          <%end%>
        <%else%>
            <% if current_user != @employee_profile.user %>
              <%= t('.no_employee_card')%>
            <% else %>
              <%= t('.no_card') %>
            <% end %>
        <%end%>
      </div>
      
    </div>
  </div>
</div>

app/views/shared/profile/_company.html.erb
<div class="card mt-3">
  <div class="card-header">
    Informações Empresariais
  </div>
  <div class="card-body">

    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('company_id') %>: <%= format_name(@employee_profile.department.company.brand_name) %></p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('department_id') %>: <%= @employee_profile.department.name %></p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('position_id') %>: <%= @employee_profile.position.name %></p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('status') %>: <%= t("activerecord.enum.employee_profile.status.#{@employee_profile.status}") %></p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('admission_date') %>:
      <%= l(@employee_profile.admission_date) %>
    </p>
    <% if @employee_profile.dismissal_date %>
      <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('dismissal_date') %>: <%= @employee_profile.dismissal_date.strftime('%d/%m/%Y') %></p>
    <% end %>
  </div>
</div>

app/views/shared/profile/_info.html.erb
<div class="card mt-3 ">
  <div class="card-header" style="background-color: #ddd">
    Perfil
  </div>
  <div class="card-body">
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('name') %>:
      <%= format_name(@employee_profile.name) %>
    </p>
    <% if @employee_profile.social_name.present? %>
      <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('social_name') %>:
        <%= @employee_profile.social_name %>
      </p>
    <% end %>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('email') %>:
      <%= @employee_profile.email %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('birth_date') %>:
      <%= @employee_profile.birth_date.strftime('%d/%m/%Y') %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('cpf') %>:
      <%= format_cpf(@employee_profile.cpf) %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('rg') %>:
      <%= @employee_profile.rg %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('address') %>:
      <%= @employee_profile.address %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('phone_number') %>:
      <%= format_number(@employee_profile.phone_number) %>
    </p>
    <p class="card-text m-1"><%= EmployeeProfile.human_attribute_name('marital_status') %>:
      <%= t("activerecord.enum.employee_profile.marital_status.#{@employee_profile.marital_status}") %>
    </p>
    <div>
      <% if current_user.manager? && @employee_profile.user != current_user %>
        <%= link_to t('.edit'),
            edit_company_department_employee_profile_path(
              @employee_profile.department.company_id,
              @employee_profile.department.id,
              @employee_profile
            ),
            class: 'btn btn-warning text-white'
        %>
        <% unless @employee_profile.fired? %>
          <%= link_to t('.fired_employee'),
            new_fired_company_department_employee_profiles_path(
              @employee_profile.department.company_id,
              @employee_profile.department.id,
              id: @employee_profile.id
            ),
            class: 'btn btn-danger'
          %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>